services:
  web:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "${port}:${port}"
      - "${port2}:${port2}"
    volumes:
      - ./:/var/www/public
      - ./000-default.conf:/etc/apache2/conf.d/000-default.conf